### ISSUE TITLE
Create awesome list

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#101]
See Yilong's [post](https://www.linkedin.com/posts/yilongzhang_creating-a-validated-environment-for-reproducibility-activity-7044529198165594112-DGf4/). It would be great to create an awesome list repo on R for clinical reporting.

**Comment by hidyverse** [comment]
Hello! I'm a data scientist at UArizona wanting to get more involved in the clinical trials space so I'm teaching with your book over the summer semester. 

I'd be super excited to contribute to/maintain an awesome list. Please let me know if you had plans to proceed.

**Comment by elong0527** [comment]
Thanks for reaching out!

Would be great if you can initiate a repo and maintain the list. Happy to review and recommend items. 

Also glad to hear feedbacks from your book club :)

**Comment by hidyverse** [comment]
Great - I started working on this at [hidyverse/awesome-R-clinical-reporting](https://github.com/hidyverse/awesome-R-clinical-reporting).
 
I would very much appreciate recommendations and considerations for a useful format to follow!!
