### ISSUE TITLE
Assessment for chapter(s) of advanced tables

### ISSUE THREAD

**Issue by allenzhuaz** [elong0527/r4csr#105]
Commonly, CSR may also contain some complex (2-Dimensional) table structure, such as 

- **exposure adjusted AE by observation period** (row header: AE SOC/PT, column header: treatment arm nested with observation period)
- **summary of lab toxicity grade shift** (row header: baseline tox grade; column header: treatment arm nested with post-baseline max tox grade) 

Shall we consider adding a chapter for producing the advanced tables?

**Comment by nanxstats** [comment]
@elong0527 what do you think?

**Comment by elong0527** [comment]
Thanks for the suggestion, I would suggest other places to discuss advanced table.

We assume limited knowledge of trial development for the target audience of r4csr. 

Understanding those tables requires more domain knowledge. For the same reason, I intentionally simplify the data structure and manipulation in the book.

I will recommend two ways to include those tables.

1. If the goal is to show advanced features in r2rtf, either write an vignettes in r2rtf or write a Phuse paper (like the ICH listing paper)

2. If we want to create a table for production use. Develop a new function/package using metalite framework is more user friendly.

Either way, we can refer those examples or tools in our book after they are completed.
