### ISSUE TITLE
Migrate to Quarto slides and fix links

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#106]
After the migration to Quarto book, some chapters' URLs have changed.

This created some broken links in the decks under the `slide/`.

For consistency, we should migrate all slides to Quarto slides and fix those links.

I will send a PR.

**Comment by elong0527** [comment]
Maybe we can keep them as is? We would not rerun those code as each slides has been finalized.

**Comment by nanxstats** [comment]
I would love to keep them as is - but the point here is to fix all the broken links - there are like 50 of them.

**Comment by elong0527** [comment]
Should be fixed by #112
