### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#111]
After the Quarto migration, all "View source" and "Edit this page" links on the website are broken because they point to the `main` branch (the default for all new GitHub repos).

So, I think it's probably a good time to change the default branch name from `master` to `main`. You can do this easily by go to the repo Settings -> General -> Default branch. It takes one minute to change.

See all context about this default branch name change at <https://github.com/github/renaming>.

**Comment by elong0527** [comment]
Done
