### ISSUE TITLE
Avoid `head()` function to control number of rows

### ISSUE THREAD

**Issue by elong0527** [elong0527/r4csr#115]
I had an impression there is a way to control default output while printing data frame. That can potentially remove the `head` function to enhance readability.

**Comment by nanxstats** [comment]
Modified from [customize the printing of objects in chunks](https://bookdown.org/yihui/rmarkdown-cookbook/opts-render.html) in R Markdown Cookbook:

```r
knit_print.data.frame <- function(x, ...) {
  paste(capture.output(base::print.data.frame(head(x, 5))), collapse = "\n")
}

registerS3method(
  "knit_print", "data.frame", knit_print.data.frame,
  envir = asNamespace("knitr")
)
```

You can add the above to [_common.R](https://github.com/elong0527/r4csr/blob/main/_common.R) to customize the printing method.
`_common.R` is sourced at the beginning of most chapters.
Remember to remove the existing `head()` calls.
