### ISSUE TITLE
Chapter Efficacy - reference to missing data 

### ISSUE THREAD

**Issue by SHAESEN2** [elong0527/r4csr#26]
I would include a book of a key opinion leader as well in the field eg https://www.wiley.com/en-us/Missing+Data+in+Clinical+Studies-p-9780470849811

**Comment by elong0527** [comment]
I have included a book that represent opinions from academia, regulatory and industry.  

The Prevention and Treatment of Missing Data in Clinical Trials.

https://www.ncbi.nlm.nih.gov/books/NBK209904/pdf/Bookshelf_NBK209904.pdf
