### ISSUE TITLE
Discuss RTF layout difference for different company 

### ISSUE THREAD

**Issue by elong0527** [elong0527/r4csr#3]
From #2 

- I think we need to be aware that many pharmaceutical companies have standards wrt layout of those tables, listings and figures

- The code you provide are for basic manipulations to get the final tbl into rtf without any layout. I think this is good, but we should consider showing wrappers that do all the layout in one go. Wrappers are typically more robust as you can easily change what happens under the hood without the user noticing it

**Comment by SHAESEN2** [comment]
When looking at the chapters with table generation, it becomes more clear that this discussion is important. As a statistical programmer you might need to create >100 TLFs and you can't be bothered with copy/paste many lines of code just to get the RTF produced. 

One example is also the indentation of tables. RTF code allows easy implementation of indents without the user have to bother with adding manual spaces.

**Comment by nanxstats** [comment]
Can we close this or do we still need more discussions in the chapter?

I guess it's reasonable to propose a theming feature for r2rtf or other packages, but that's going to happen in its own repo.

**Comment by elong0527** [comment]
I would keep this one open. I will draft a more clear statement of the potential different layout for different organization. 

I am also interested in learning more of the progress the `tgen` project that may be helpful to build different theming feature.
