### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#32]
We should add a license disclaimer to the landing page (with a `LICENSE` file) like https://mastering-shiny.org/ did.

**Comment by elong0527** [comment]
I did not find a statement in all the bookdown project:

e.g. https://r-pkgs.org/index.html

what license would you recommend? Shall this be handled only if the book needs to be published with a publisher?

**Comment by nanxstats** [comment]
So R4DS has a license statement on landing page https://r4ds.hadley.nz/ as in Mastering Shiny.

Advanced R and R Packages both have a license file in repo although not explicitly stated:

- https://github.com/hadley/adv-r/blob/master/LICENSE.md
- https://github.com/hadley/r-pkgs/blob/main/LICENSE

I feel it is a good practice that we clarify the license for any open source projects, regardless of publishing formally or not.

I'm not really in the position of giving legal advices but it looks CC BY-NC-ND 4.0 (Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License) could be a choice as used by Hadley's most recent book Mastering Shiny.

**Comment by nanxstats** [comment]
Closed by https://github.com/elong0527/r4csr/pull/34
