### ISSUE TITLE
figure or listing to be added?

### ISSUE THREAD

**Issue by allenzhuaz** [elong0527/r4csr#36]
Seemingly current TLFs part chapters mainly focus on tables produced by `tidyverse`, `table1`, `r2rtf` etc., will typical figure or listing as part of TLFs be added in some chapter?

**Comment by elong0527** [comment]
Good point. Would you willing to draft a chapter for figure generation? 

The current example in r2rtf is minimal. https://merck.github.io/r2rtf/articles/example-figure.html

If would be helpful to create figures related to CSR. (e.g. KM plot)

**Comment by allenzhuaz** [comment]
> Good point. Would you willing to draft a chapter for figure generation?
> 
> The current example in r2rtf is minimal. https://merck.github.io/r2rtf/articles/example-figure.html
> 
> If would be helpful to create figures related to CSR. (e.g. KM plot)

yes, will start it from KM plot using the pilot data

**Comment by nanxstats** [comment]
Closed by https://github.com/elong0527/r4csr/pull/40

@allenzhuaz I see you have a todo item in tlf-efficacy-km.Rmd line 48, please create a new issue for that if you want.
