### ISSUE TITLE
Improve figure quality in efficacy-figure chapter

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#45]
A few things that can be improved:

- Is it intentional to display the figure before the "Analysis dataset" section? I see it was printed in the end.
- The text in the printed figure from `ggsave()` is squeezed - might need to adjust the dimensions and dpi stuff.
- Font family: It looks like Times New Roman is not available from the GitHub Actions build environment so it's being replaced by a default serif font (Liberation Serif). Plus the text inside the box and in the risk table are not using this and are being displayed as sans serif. We probably prefer a simple solution that works consistently.

**Comment by nanxstats** [comment]
If we really need Times New Roman specifically, it is available from the Debian package `ttf-mscorefonts-installer` and thus can be installed in the Action. Then we will need some experiments to see how to set them correctly in ggplot2 plots under bookdown.

**Comment by elong0527** [comment]
@allenzhuaz, could you help on this item? 

1. We can display the PDF output as other TLF rmd file. 
2. We do not need to specify font in this example.

**Comment by nanxstats** [comment]
PR https://github.com/elong0527/r4csr/pull/46 minimized issue 3 from the system side - now Times New Roman and Arial (among others) are available from the build environment. They can be correctly rendered in the figures.

Solution from the R code side is still needed.

**Comment by nanxstats** [comment]
Closed by https://github.com/elong0527/r4csr/pull/49
