### ISSUE TITLE
Automate RTF to PDF conversion

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#47]
We should install libreoffice in the build environment and automate the rtf to pdf conversion.

This should render the PDFs correctly as now the MS fonts are available from PR https://github.com/elong0527/r4csr/pull/46.

I would suggest we use a simple `system()` call to do the conversion, since `r2rtf:: rtf_convert_format()` is currently version-dependent (libreoffice 7.1 is not yet available from the official package repo of Ubuntu 20.04 LTS which the GitHub Action uses).

What do you think? @elong0527

**Comment by elong0527** [comment]
I agree if there is a way to remove version dependency. I learned this code from IT team. Could you guide me how to enable this?

**Comment by nanxstats** [comment]
I created a separate issue for r2rtf on improving program discovery: https://github.com/Merck/r2rtf/issues/64

I will create a PR to solve this issue using the simple system call method I mentioned.

Once r2rtf is patched, we can easily replace the system call with it.

**Comment by nanxstats** [comment]
Closed by https://github.com/elong0527/r4csr/pull/48
