### ISSUE TITLE
Prefix verbs in R with package

### ISSUE THREAD

**Issue by SHAESEN2** [elong0527/r4csr#5]
It is considered good programming practice to prefix the verbs used with the package name eg #4 
- Considering the vast amount of (redundant) packages
- Considering the known conflicts to cause issues eg lag/filter 
- A user can immediately see which packages are used and can request more information quickly if they are not familiar with specific verbs eg pivot_wider

**Comment by elong0527** [comment]
I agree it is a good practice to add prefix for real project. (Also share the pain for `filter` and other function result in conflicts of different namespace)

For the tutorial, I would keep using function name only for simplicity. This is also consistent with other book such as R for data science.

**Comment by SHAESEN2** [comment]
OK.
