### ISSUE TITLE
Efficacy KM plot

### ISSUE THREAD

**Issue by SHAESEN2** [elong0527/r4csr#50]
I propose to use the visR package instead of survminer. This package was specifically created to be compatible with clinical data analysis and leverages ADaM structure, is more user-friendly, and a higher testing coverage.

[vignettes/tlf-kmplot.Rmd](https://github.com/RConsortium/submissions-pilot1/blob/b253455a9fba135dc0421b1c23e4857868e29100/vignettes/tlf-kmplot.Rmd)

**Comment by elong0527** [comment]
For both `survminer` and `visR`, I feel the dependency is heavy for a book and may break the project with newer version of the package. 

I probably suggest to create a simplified version of KM plot using `survival` and refer the two packages in the text. 

@allenzhuaz, how would you feel?

**Comment by nanxstats** [comment]
I see this

```r
db <- available.packages(repos = "https://cloud.r-project.org")
tools::package_dependencies("visR", db = db, recursive = TRUE)[[1]] |> length()
#> [1] 126
tools::package_dependencies("survminer", db = db, recursive = TRUE)[[1]] |> length()
#> [1] 132
```

So they look pretty heavy indeed.

**Comment by timtreis** [comment]
Hey there! Just chiming in after a quick chat I had with Steven a few minutes ago. Thanks for pointing out our rather heavy package load, that prompted us to investigate and we indeed found a lot of stuff that we could let go of.

In our next release (December probably) we'll release a new version to CRAN that implements a bunch of new features and then reduces the dependencies as well. I didn't use your exact code since I wanted to run it on our `develop` branch, but here is the comparison for that.
```
library(dplyr)
devtools::install_github("r-lib/pkgdepends")

pd_visR <- pkgdepends::new_pkg_deps("openpharma/visR")
pd_visR$solve()
pd_visR_res <- pd_visR$get_resolution()
nrow(pd_visR_res) # -> 86

pd_survminer <- pkgdepends::new_pkg_deps("kassambara/survminer")
pd_survminer$solve()
pd_survminer_res <- pd_survminer$get_resolution() 
nrow(pd_survminer_res) # -> 149

pd_r4csr <- pkgdepends::new_pkg_deps("elong0527/r4csr")
pd_r4csr$solve()
pd_r4csr_res <- pd_r4csr$get_resolution() 
nrow(pd_r4csr_res) # -> 206

base::setdiff(pd_visR_res$ref, pd_r4csr_res$ref)
# -> "openpharma/visR"
base::setdiff(pd_survminer_res$ref, pd_r4csr_res$ref)
# -> "kassambara/survminer"

```

While neither `survminer` nor `visR` would add new dependencies to the repository anyway, our upcoming release will be quite a bit lighter than `survminer`. Would you reconsider Steven's suggestion after our next release? :)

**Comment by elong0527** [comment]
Thanks for improving the dependency for `visR`. This change is also simplify the required package qualification steps for `visR`. 

As `r4csr` also use `tidyverse`, I think majority of dependency R packages in `visR` have been covered in the new release. 

We will evaluate it after the new release.

**Comment by allenzhuaz** [comment]
> For both `survminer` and `visR`, I feel the dependency is heavy for a book and may break the project with newer version of the package.
> 
> I probably suggest to create a simplified version of KM plot using `survival` and refer the two packages in the text.
> 
> @allenzhuaz, how would you feel?


> I see this
> 
> ```r
> db <- available.packages(repos = "https://cloud.r-project.org")
> tools::package_dependencies("visR", db = db, recursive = TRUE)[[1]] |> length()
> #> [1] 126
> tools::package_dependencies("survminer", db = db, recursive = TRUE)[[1]] |> length()
> #> [1] 132
> ```
> 
> So they look pretty heavy indeed.

Thanks @nanxstats for current `survminer` and `visR` dependency checking, given the available package versions, I would agree with @elong0527 suggestion, will revise this chapter starting with `survival` package for basic KM plot display and may provide equivalent example with using `visR` or `survminer`.

Also thanks @SHAESEN2 for the submission pilot example with `visR` and `ggplot2`

**Comment by allenzhuaz** [comment]
#57

**Comment by nanxstats** [comment]
Can this issue be closed as the updated chapter is already there?
