### ISSUE TITLE
Invalid SAS data files

### ISSUE THREAD

**Issue by zuoyi93** [elong0527/r4csr#58]
Hi,

Thanks for making this amazing repository! I wanted to quickly ask if the SAS data files under the data-adam directory are still valid. 

I tried to load one of the files with `adsl <- read_sas("data-adam/adsl.sas7bdat")`, but R gave me the following warning "Error: Failed to parse data-adam/adsl.sas7bdat: Invalid file, or file has unsupported features." I also tried to open the file with SAS directly. SAS then gave me the following error.
![image](https://user-images.githubusercontent.com/25957920/147376577-bf583191-f887-4419-bf08-15bd020ba45a.png)

Thanks in advance!

Yi

**Comment by elong0527** [comment]
I am able to open the ADSL data both from R and SAS from my end. 

Could you share your session information in R?

**Comment by nanxstats** [comment]
I think you might want to check if the files are somehow corrupted (e.g. when being cloned). Running

```r
data.frame(tools::md5sum(list.files("data-adam/", full.names = TRUE)), fix.empty.names = FALSE)
```

gives their md5 hashes:

```                                                      
data-adam//adae.sas7bdat     0f8b432f089a75aee71c980fcd7c8f9f
data-adam//adlbc.sas7bdat    09fa39cedbcc3bcb3defeabdbbc99ed9
data-adam//adlbh.sas7bdat    d5a997cef8fe1a83e243fe508cbb6ebc
data-adam//adlbhy.sas7bdat   7c17a249e2c7c0aacbd9d3778dd5c382
data-adam//adqsadas.sas7bdat 8ce022663c0f4d17330b954d678a3a2e
data-adam//adqscibc.sas7bdat 6762a4cc97b8503c309791c21427e5b2
data-adam//adqsnpix.sas7bdat 9ccac393db5dac59f9e4c08cd0d34080
data-adam//adsl.sas7bdat     51abb0d68fd9f629f5c2a3685382da1b
data-adam//adtte.sas7bdat    7a311cf74f1ddf70eca03fed7dbddaa9
data-adam//advs.sas7bdat     de2ace78c29a122929c9f1c9cefa5a94
```

**Comment by zuoyi93** [comment]
Thanks for your prompt response! The files were corrupted. Now I am able to read those data in R. Thanks again!
