### ISSUE TITLE
Add rtf assemble chapter

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#79]
We should add a chapter on assembling TLFs to an RTF file.

Currently, there is one internal workflow bookdown chapter about this (with two sections on using `rtf_assemble()` and using toggle fields). Do we want to use some of that content as a starter?

Also, pending the availability of `rtf_assemble()` from r2rtf.

cc @elong0527 @LittleBeannie @wangben718

**Comment by elong0527** [comment]
Sure, if you could start a branch with existing version, I will add additional details.

**Comment by LittleBeannie** [comment]
I upload the rtf-asemble rmd into the #79 branch. I am not sure if the study example is confidential, so I mask the study number as mkxxx-pxxx. Besides, I didn't upload the images, since there are numbers in the figures, and I am not sure if this study is public or not.

**Comment by nanxstats** [comment]
Hmm, I'm not exactly comfortable with some of the text shared in that branch so I just removed it. Let me volunteer here to write a clean version in another branch for you guys to work on.

**Comment by nanxstats** [comment]
Fixed by https://github.com/elong0527/r4csr/pull/82
