### ISSUE TITLE
Remove inline code style for package names

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#91]
I suggest we make a consistency fix to not stylize R package names as inline code, such as `r2rtf`.

This would make it consistent with the styling practices in Hadley's books, such as adv-r, r-pkgs, ggplot2-book.

Since we are using package names a lot in the text, I also don't think rendering them as emphasized text (bold or italic) is optimal. See [bold or italic](https://practicaltypography.com/bold-or-italic.html) for the reasoning.

@elong0527 What do you think?

**Comment by elong0527** [comment]
I can make the change, what’s the recommendation for package name style?

**Comment by nanxstats** [comment]
Good. I can provide two data points:

- In Hadley's books, package names are not stylized at all.
- In Yihui's books, package names are **bold**.

So it's up to you.

**Comment by nanxstats** [comment]
Fixed by https://github.com/elong0527/r4csr/pull/94
